# Generated by Django 5.2.3 on 2025-06-18 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qarecord',
            old_name='timestamp',
            new_name='answered_at',
        ),
        migrations.AddField(
            model_name='qarecord',
            name='asked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
